# Generated by Django 5.0.7 on 2024-07-20 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceApp', '0007_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='imagen',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
